### ISSUE TITLE
Custom domain for object storage makes URL function serve incorrect path

### ISSUE THREAD

**Issue by Seiferek** [dennisv/django-storage-swift#90]
My mistake. Nevermind. Good Job!

BTW. It's possible to serve one type of file from other object storage?
E.g:
JS files from object storage [1]
CSS files from object storage [2]
TXT files from object storage [3]
etc.?

**Comment by einarf** [comment]
I'm sure it's possible to support splitting files up in different storage backends, but that's more up to the ``staticfiles`` package in Django. You could customize that to fit your needs.
